### ISSUE TITLE
Deploying to Heroku or Openshift Assistance

### ISSUE THREAD

**Issue by brianjking** [Axiacore/knowledge-base#39]
Hi @Axiacore -- Just saw your knowledgebase repo and it looks lovely.

Is it pretty stable as of right now? Any info on how to deploy to Heroku or Openshift Online?

Thanks!

**Comment by camilonova** [comment]
@brianjking It should be fairly easy to deploy, it is just a standard django project.

Please let us know how it goes for you :)

**Comment by brianjking** [comment]
@camilonova I followed the instructions provided here:

```
Copy local_settings.py.template to local_settings.py and fill in your information. Have in mind that SITE_URL should be the url where you are hosting this project, and ALLOWED_DOMAINS should be the domains of the emails that are allowed to login and view private articles.
```

I then ran:
- `git add local_settings.py -f`
- `git commit -m "settings"`
- `git push heroku`

Heroku build fails:

```
 $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "manage.py", line 22, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 196, in fetch_command
           settings.INSTALLED_APPS
         File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
           self._setup(name)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
           self._wrapped = Settings(settings_module)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 116, in __init__
           raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
       django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

Secondly, how do I go about getting the secret key https://github.com/Axiacore/knowledge-base/blob/master/app/local_settings.py.template

Thanks!

**Comment by brianjking** [comment]
@camilonova Okay, I think I got the secret key worked out.

What about the `Procfile` that Heroku requires? https://devcenter.heroku.com/articles/python-gunicorn#adding-gunicorn-to-your-application

**Comment by camilonova** [comment]
@brianjking If you create the Procfile send us a PR to add into the project, including any other information you might think is important when deploying to Heroku

**Comment by brianjking** [comment]
@camilonova I'm working on it in my own fork/branch and will submit a PR if I ever get it working.

I've got it working for the most part, outside of the Django static file serving issue I do believe. See: https://guarded-ridge-41738.herokuapp.com/

Where are you deploying this without this trouble?

**Comment by camilonova** [comment]
@brianjking We use a Digital Ocean Droplet

**Comment by brianjking** [comment]
@camilonova If I try to go the docker-compose route as per your readme I receive this error:

docker-compose up                                                                                                    11:14   08.09.16
Pulling npm (knowledgebase:latest)...
Pulling repository docker.io/library/knowledgebase
ERROR: Error: image library/knowledgebase:latest not found

**Comment by camilonova** [comment]
Please do first `docker-compose build`

**Comment by brianjking** [comment]
@camilonova Okay, I got it working finally this way. However, now I'm trying to get it to work with Gunicorn & NGINX. Using `python manage.py runserver` is definitely not suitable for running a production app.

I'm having trouble getting this to work inside of the `docker-compose.yml`, however, I guess I'll keep looking at it when I have time.
- http://serverfault.com/questions/717568/risks-of-using-django-manage-py-runserver-for-production-in-a-small-scale-server
- https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-option---nothreading
